openapi: 3.0.0
info:
  title: mod-authtoken API
  version: v1
paths:
  # NOTE This module relies on its folio-vertx-lib dependency to handle the /_/tenant
  # route. Please see its yaml specification for /_/tenant here:
  # https://dev.folio.org/reference/api/#folio-vertx-lib
  /token:
    parameters:
      # folio-vertx-lib has header files but they don't make the headers required so we override
      # that behavior here since these two headers are required.
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Returns a signed, non-expiring legacy access token.
      operationId: token-legacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signTokenPayload"
        required: true
      responses:
        "201":
          description: Created and signed token successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponseLegacy"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /refreshtoken:
    parameters:
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: |
        Returns a signed, expiring refresh token. This is a legacy endpoint and should not be
        called by new code and will soon be fully depreciated.
      operationId: token-sign-legacy
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signRefreshToken"
        required: true
      responses:
        "201":
          description: Created and signed token successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /token/sign:
    parameters:
      # folio-vertx-lib has header files but they don't make the headers required so we override
      # that behavior here since these two headers are required.
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: |
        Returns a signed, expiring access token and refresh token. Also returns the expiration
        of each token in the body of the response.The access token time to live is 10 minutes and
        the refresh token is one week.
      operationId: token-sign
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signTokenPayload"
        required: true
      responses:
        "201":
          description: Created and signed tokens successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponse"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /token/refresh:
    parameters:
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: |
        May be called to obtain a new refresh token and a new access token. Returns a signed, expiring
        access token and refresh token. Also returns the expiration of each token in the body of the
        response. The access token time to live is 10 minutes and the refresh token is one week.
      operationId: token-refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refreshToken"
        required: true
      responses:
        "201":
          description: Refreshed tokens successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/tokenResponse"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /token/logout:
    parameters:
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Logout a single token
      operationId: token-logout
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refreshToken"
        required: true
      responses:
        "204":
          description: Logged out token successfully
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /token/logout-all:
    parameters:
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Logout all tokens for a user
      operationId: token-logout-all
      responses:
        "204":
          description: Logged out token successfully
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: { "error": "Invalid JSON in request" }
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    refreshToken:
      $ref: schemas/refreshToken.json
    tokenResponse:
      $ref: schemas/tokenResponse.json
    tokenResponseLegacy:
      $ref: schemas/tokenResponseLegacy.json
    signTokenPayload:
      $ref: schemas/signTokenPayload.json
    signRefreshToken:
      $ref: schemas/signRefreshToken.json
    token:
      $ref: schemas/token.json
