openapi: 3.0.0
info:
  title: mod-authtoken API
  version: v1
paths:
  # NOTE This module relies on the its folio-vertx-lib dependency to handle the /_/tenant
  # route. Please see its yaml specification for /_/tenant here:
  # https://dev.folio.org/reference/api/#folio-vertx-lib
  /token:
    parameters:
      # folio-vertx-lib has header files but they don't make the headers required so we override
      # that behavior here since these two headers are required.
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Sign token
      operationId: token
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signTokenPayload"
        required: true
      responses:
        "201":
          description: Created and signed token successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /token/sign:
    parameters:
      # folio-vertx-lib has header files but they don't make the headers required so we override
      # that behavior here since these two headers are required.
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Sign token
      operationId: token-sign
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signTokenPayload"
        required: true
      responses:
        "201":
          description: Created and signed token successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"

  /refresh:
    parameters:
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Sign token
      operationId: refresh
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/refreshToken"
        required: true
      responses:
        "201":
          description: Created and signed token successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
  /refreshtoken:
    parameters:
      - $ref: headers/okapi-tenant-required.yaml
      - $ref: headers/okapi-url-required.yaml
    post:
      description: Sign token
      operationId: refreshtoken
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/signRefreshToken"
        required: true
      responses:
        "201":
          description: Created and signed token successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/token"
        "400":
          $ref: "#/components/responses/trait_400"
        "500":
          $ref: "#/components/responses/trait_500"
components:
  responses:
    trait_400:
      description: Bad request
      content:
        text/plain:
          schema:
            type: string
            example: Invalid JSON in request
        application/json:
          schema:
            type: object
            example: { "error": "Invalid JSON in request" }
    trait_500:
      description: Internal error
      content:
        text/plain:
          schema:
            type: string
            example: Internal server error, contact administrator
  schemas:
    refreshToken:
      $ref: schemas/refreshToken.json
    signRefreshToken:
      $ref: schemas/signRefreshToken.json
    token:
      $ref: schemas/token.json
    signTokenPayload:
      $ref: schemas/signTokenPayload.json
